version: '3.8'

services:
    postgres-db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres

    redis-db:
        image: redis:latest

    server:
        restart: unless-stopped
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_URL=redis://redis-db:6379
            - POSTGRES_URL=postgres://postgres:postgres@postgres-db:5432/postgres
    
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app

    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_URL=redis://redis-db:6379
            - POSTGRES_URL=postgres://postgres:postgres@postgres-db:5432/postgres
    
    nginx-router:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
          - "8080:80"
